; SET DEFAULT BAUD RATE AND HALF/FULL DUPLEX. VALUES SHOWN
;	ARE FOR A 2 MHZ CLOCK. NUMBERS SHOWN FOR FULL DUPLEX:
;	ADD 1 FOR HALF DUPLEX.
	           ;   75 BAUD = 0A2H
	           ;  110 BAUD = 06CH
;	LDI  26H   ;  300 BAUD = 026H, Loren: original default.
	           ;  600 BAUD = 012H		
	LDI  08H   ; 1200 BAUD = 008H
	PHI  RE       
	GHI  R0 	; INITIALIZE DELAY SUBROUTINE PC
	PHI  RC
	LDI  LOW DELAY1
	PLO  RC
	LDI  0DH	;   SEND <CR> TO BASIC
	SEP  R5 	; < TO EXECUTE "RUN" COMMAND